#gui module
from tkinter import *
from tkinter import ttk
from tkinter import messagebox
from tkinter import filedialog
import tkinter.simpledialog as simpledialog
import tkinter

import sys
import random
#crypto
from cryptography.fernet import Fernet
import base64
import os
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC

#file saving
#pickle can save objects as str and turn them back into objects
import pickle

from PIL import Image
#alphabet module
import string 

class Grid():
    def make_grid(self,size): #makes 2D list for the size given by the user when the game is started
        self.newGrid = [['0' for i in range(size)]for j in range(size)]
        Grid.playerGrid = self.newGrid
        self.oNewGrid= [['0' for i in range(size)]for j in range(size)]
        Grid.oponentGrid = self.oNewGrid
        #return (self.newGrid)              
                
    def get_letters(self,a):
        self.letters = string.ascii_uppercase #stores the letters of the alphabet in uppercase 
        return self.letters[a]

    def fire(self,i,j):
        print("You have fired at ", i , j )
        if Grid.oponentGrid[i][j] =='B':
            Grid.oponentGrid[i][j] ='H'
            print("it's a hit")
            MenuGUI.changeOponentSquareIcon(self)
        elif Grid.oponentGrid[i][j]== '0':
            print("It's a miss")
            Grid.oponentGrid[i][j] = 'M'
            MenuGUI.changeOponentSquareIcon(self)

        
class SaveState(Grid):
    #code written from https://www.youtube.com/watch?v=H8t4DJ3Tdrg
    #this class uses basic encryption to encrypt the text in the state of the game. This prevents players from cheating by looking at the game file
    

    def locateKeyOrCreateOne(self):
        #This function returns a .key file with an encryption key
        #I have changed this to utilise a password keyword instead so there are less files floating about

        if messagebox.askyesno(message='Would you like to find an existing crypto key?') == True:
            self.fileName = filedialog.askopenfilename(title='Locate Battleships.key',defaultextension='.key',initialfile='battleships.key')
            self.keyFile = open(self.fileName,'rb')
            self.Key = self.keyFile.read()
            self.keyFile.close()
            print("Opened crypto key from: ",self.fileName)
        else:
            self.fileName = filedialog.asksaveasfile(title='Save Battleships.key',defaultextension='.key',initialfile='battleships.key')
            self.keyFile = open(self.fileName.name,'wb')
            self.genKey = Fernet.generate_key()
            print(self.genKey)
            self.keyFile.write(self.genKey)
            self.keyFile.close()
            self.keyFile = open(self.fileName.name,'rb')
            self.Key = self.keyFile.read()
            self.keyFile.close()
            print("Saved crypto key to: ",self.fileName.name) 
        print(self.Key)

    def passwordEncryption(self):
        #this function returns a key generated by a password. 
        #Players can send their oponent a unique passphrase which will encrpyt the game state and can still be
        # unencrypted by the oponent remotely.
        #  
        self.passPhraseProvided = simpledialog.askstring(title="Passphrase",prompt="Enter you passphrase. (This needs to be the same as your oponent.)")
        self.password = self.passPhraseProvided.encode()
        self.salt = b'\xc4"et\x8e\xb7\x98\xce\xcc.\xb2\xdb\x07\x84\xc3\xbc'
        self.kdf = PBKDF2HMAC(algorithm=hashes.SHA256(),length=32,salt=self.salt,iterations=100000)
        self.key = base64.urlsafe_b64encode(self.kdf.derive(self.password))
        print(self.key) 
        self.hintText2.set("Once you've placed your ships, click save and send the file to your oponent")

    def encryptMessageToFile(self):
        self.gameGrids = [Grid.playerGrid, Grid.oponentGrid]
        self.message = pickle.dumps(self.gameGrids)
        encodedMessage = self.message
        f = Fernet(self.key)
        self.encryptedMessage = f.encrypt(encodedMessage)
        print(self.encryptedMessage)
        self.fileName = filedialog.asksaveasfile(title='Save game file',defaultextension='.config',initialfile='battleships.config')
        self.gameFile = open(self.fileName.name,'wb')
        self.gameFile.write(self.encryptedMessage)
        self.gameFile.close()
        print("Saved game state to :",self.fileName.name)

        
    def saveGame(self):
        #SaveState.locateKeyOrCreateOne(self)
        SaveState.passwordEncryption(self)
        SaveState.encryptMessageToFile(self)
        return

    def openState(self):
        SaveState.passwordEncryption(self)
        self.fileName = filedialog.askopenfilename(title='Locate game file',defaultextension='.config',initialfile='battleships.config')
        self.gameFile = open(self.fileName,'rb')
        self.encryptedOpen = self.gameFile.read()
        self.gameFile.close()
        f2 = Fernet(self.key)
        self.decrypted = f2.decrypt(self.encryptedOpen)
        self.pickledBoard = self.decrypted
        self.messageOpen = pickle.loads(self.pickledBoard)
        Grid.playerGrid = self.messageOpen[1]
        Grid.oponentGrid = self.messageOpen[0]
        MenuGUI.changePlayerSquareIcon(self)
        MenuGUI.changeOponentSquareIcon(self)

        

        return




class Ships(Grid):
    
    #function when a square is clicked and boat is placed
    def place_ship(self,i,j):
        print()
        while True:
            try: 
                self.tempShip=[]
                self.tempList = []
                self.selectedI = i
                self.selectedJ = j
                for n in range(self.shipSize):
                    Grid.playerGrid[i+n][j] = 'B'
                    self.tempList = []
                    self.tempList.append(i+n)
                    self.tempList.append(j)
                    self.tempShip.append(self.tempList)

                    MenuGUI.changePlayerSquareIcon(self)
                self.shipCount =sum(row.count('B') for row in Grid.playerGrid)
                print("Square ( %i,%i ) = "%(i,j)   , Grid.playerGrid[i][j] , ". Ship count: " , self.shipCount)
                print(self.tempShip)
                self.shipSize = self.shipSize-1
                if self.shipCount >=15:
                    MenuGUI.disableAllPlayerButtons(self)
                    self.hintText1.set("Thank You. Please now select a square to fire at your oponent")
                else:
                    self.hintText1.set("Now select where your battleship of length %i is placed" % self.shipSize)

                break
            except:
                    messagebox.showerror("Outside of Range","You have entered a square outside the grid, normal function will not be available")
                    break
        def computer_place_ships(self):
            while True:
                try:

                    for n in range(5):
                        i = random.randint(0,self.size)
                        j = random.randint(0,self.size)
                        for m in range(n):
                            Grid.oponentGrid[i+n][j] = 'B'
                    break
                except:
                    messagebox.showerror("Outside of Range","You have entered a square outside the grid, normal function will not be available")
                    break



            

                    
    def rotate90(self):
        #while True:
            #try:
                i = self.selectedI
                j = self.selectedJ
                self.tempShipBefore = self.tempShip
                for n in range (1,self.shipSize+1):
                    Grid.playerGrid[(self.tempShip[n][0])][(self.tempShip[n][1])] = '0'
                    
                    
                    
                    x = self.tempShip[n][0]
                    y = self.tempShip[n][1]
                    xB = i+j-y
                    yB = -i+j+x
                    x=xB
                    y=yB
                    Grid.playerGrid[x][y]='B'
                    MenuGUI.changePlayerSquareIcon(self)
                print(self.tempShip)
                #break
            #except:
                #messagebox.showerror("Outside of Range","You have entered a square outside the grid, normal function will not be available")
                #break
                


        #tempButton = MenuGUI.playerGridButtons[i][j]
        #tempButton.config(bg='red')



class MenuGUI(Frame,Ships,Grid):
    def __init__(self,root): 
        
        root.title("Battleships")#sets the title of the window
        


        #setup file save encryption

        #self.key = Fernet.generate_key()
        #self.keyFile = open('key.key','wb')
        #self.keyFile.write(self.key)
        #self.keyFile.close()

        #sets the icon for the UI
        path = "D:/BBC Apprenticeship/University/Semester 3/Programming/COURSEWORK/Icons/"

        self.icon = PhotoImage(file= path + "ship.png")
        root.iconphoto(False,self.icon)
        

        #imports photo icons
        self.hitImg = PhotoImage(file= path + "hit.png" )
        self.emptyImg = PhotoImage(file= path + "empty.png")
        self.boatImg = PhotoImage(file= path + "ship_body.png")

        self.smallEmptyImg = PhotoImage(file = path + "/oponent_icons/empty.png")
        self.smallHitImg = PhotoImage(file = path + "/oponent_icons/hit.png")
        self.smallMissImg = PhotoImage(file = path + "/oponent_icons/miss.png")
    

        #make the frames for the GUI
        self.mainMenuFrame = ttk.Frame(root, padding="3 3 12 12")
        self.mainMenuFrame.grid(column=0, row=0, sticky=(N, W, E, S))
        self.middleFrame = ttk.Frame(root,padding="3 3 12 12")
        self.middleFrame.grid(column=1,row=0,sticky=(N, W, E, S))
        self.rightFrame = ttk.Frame(root,padding="3 3 12 12")
        self.rightFrame.grid(column=2,row=0,sticky=(N, W, E, S))
        self.playerBoardFrame = ttk.Frame(self.middleFrame,padding="3 3 12 12")
        self.playerBoardFrame.grid(column=0,row=0,sticky=(N, W, E, S))
        self.oponentBoardFrame = ttk.Frame(self.rightFrame, padding="3 3 12 12")
        self.oponentBoardFrame.grid(column=0,row=0,sticky=(N, W, E, S))
        self.placeshipsFrame = ttk.Frame(self.middleFrame,padding="3 3 12 12")
        self.placeshipsFrame.grid(column=0,row=1)
        root.columnconfigure(0, weight=1)
        root.rowconfigure(0, weight=1)	



        #setup for dropdown list
        self.gridList = ['','6x6','8x8','10x10','12x12','14x14','16x16']
        self.defListItem = StringVar(root)
        self.defListItem.set(self.gridList[3]) #default value


    
        #gui elements

        #main menu frame Gui (left)

        
        #image
        ##insert image code here##

        #name label
        ttk.Label(self.mainMenuFrame, text= "Battleships!").grid(row=2,column=2,sticky=(W,E))        

        #dropdown description label
        ttk.Label(self.mainMenuFrame, text= "Grid Size:").grid(row=3,column=1,sticky=(W,E))

        #dropdown grid size selection
        ttk.OptionMenu(self.mainMenuFrame,self.defListItem,*self.gridList).grid(row=3,column=2,sticky=(W,E))

        #load game button ##add command##
        self.fileSaveButton = ttk.Button(self.mainMenuFrame,text="Save game config",command = lambda: SaveState.saveGame(self),state='disabled')
        self.fileSaveButton.grid(row=4,column=2,sticky=(W,E)) 

        self.fileOpenButton = ttk.Button(self.mainMenuFrame,text="Open game config",command = lambda: SaveState.openState(self),state='disabled')
        self.fileOpenButton.grid(row=4,column=3,sticky=(W,E)) 

        #player number label new game
        ttk.Label(self.mainMenuFrame, text= "New Game:").grid(row=5,column=1,sticky=(W,E))

        #1 player  button ##add command##
        ttk.Button(self.mainMenuFrame,text="1 Player").grid(row=5,column=2,sticky=(W,E))        

        #2player  button 
        ttk.Button(self.mainMenuFrame,text="2 Player",command=self.twoPlayerBtn).grid(row=5,column=3,sticky=(W,E))

        #instruction text label
        self.hintText1=tkinter.StringVar()
        self.hintText1.set("Select Grid size then select 1 or 2 players")
        self.hintLbl1 = ttk.Label(self.mainMenuFrame,textvariable=self.hintText1).grid(row=6,column=1,columnspan=3)

        self.hintText2=tkinter.StringVar()
        self.hintText2.set("To load a file, create a game with the correct grid size")
        self.hintLbl2 = ttk.Label(self.mainMenuFrame,textvariable=self.hintText2).grid(row=7,column=1,columnspan=3)  
       
        for child in self.mainMenuFrame.winfo_children():#adds padding
            child.grid_configure(padx=2, pady=5)

        #tempory player and oponent board frame GUI elements (both)
        for i in range (2*(self.gridList.index(self.defListItem.get()))+4):
            for j in range (2*(self.gridList.index(self.defListItem.get()))+4):
                ttk.Button(self.oponentBoardFrame,width=3,state='disabled').grid(row=i,column=j)
                ttk.Button(self.playerBoardFrame,width=3,state='disabled').grid(row=i,column=j)

                #text=str(i)+','+str(j)

        #place ships buttons size
        self.shipSizeButtons = [] 
        for i in range (5):
            self.shipSizeButtons.append(ttk.Button(self.placeshipsFrame,text=str(i+1),width=3,state='disabled'))
            self.shipSizeButtons[i].grid(column=i,row=0)
        

        
    

    def updateGUI(self):
        self.size = (2*(self.gridList.index(self.defListItem.get()))+4)
        Grid.make_grid(self,self.size)
        self.fileSaveButton.configure(state='enable')
        self.fileOpenButton.configure(state='enable')

        #remove previous grid
        for child in self.oponentBoardFrame.winfo_children():
            child.destroy()
        for child in self.playerBoardFrame.winfo_children():
            child.destroy()

        self.shipCount = 0
        self.shipSize = 5

        self.rotateButton = ttk.Button(self.placeshipsFrame,text="Rotate 90",command = lambda:  Ships.rotate90(self))
        self.rotateButton.grid(column=1,row=1,columnspan=3)

        #create new grid of size n
        


        self.playerGridButtons = []
        self.oponentGridButtons = []
        for i in range (self.size):
            
            self.playerGridButtons.append ([])
            self.oponentGridButtons.append([])
            
            for j in range (self.size):
                ttk.Label(self.playerBoardFrame,text=Grid.get_letters(self,j)).grid(row=0,column=j+1)
                ttk.Label(self.oponentBoardFrame,text=Grid.get_letters(self,j)).grid(row=0,column=j+1)
                ttk.Label(self.playerBoardFrame,text=i+1).grid(row=i+1,column=0)
                ttk.Label(self.oponentBoardFrame,text=i+1).grid(row=i+1,column=0)
                ##(ADD FUNCTION)
                tempOponentButton = ttk.Button(self.oponentBoardFrame,width=3,state = 'disabled',image = self.smallEmptyImg, command = lambda i=i, j=j: Grid.fire(self,i,j))
                tempOponentButton.grid(row=i+1,column=j+1)
                self.oponentGridButtons[i].append(tempOponentButton)

                tempPlayerButton = ttk.Button(self.playerBoardFrame,width=3,image = self.emptyImg,command =  lambda i=i, j=j:  Ships.place_ship(self,i,j))
                tempPlayerButton.grid(row=i+1,column=j+1)
                self.playerGridButtons[i].append(tempPlayerButton)
                
               



    
    def twoPlayerBtn(self):
        self.updateGUI()
        
        Grid.make_grid(self,self.size)

        self.hintText1.set("Now select where your battleship of length %i is placed" % self.shipSize)
        self.hintText2.set("To load a file, select load Game from file")

        print("Player 2 Button Click. Grid size: " + str(self.size))
        print(Grid.playerGrid)

        #disable menu buttons 
        #add save to file button

    def changePlayerSquareIcon(self):
        #'NoneType' object not subscriptable
        #ttk buttons cannot hold colours
        #ttk button image
        #MenuGUI.playerGridButtons[i+1][j+1].config()
        for x in range (self.size):
            for y in range (self.size):
                if Grid.playerGrid[x][y] == 'B':
                    self.playerGridButtons[x][y].configure(image=self.boatImg,state='disabled')
                elif Grid.playerGrid[x][y] == '0':
                    self.playerGridButtons[x][y].configure(image=self.emptyImg,state='enabled')
                elif Grid.playerGrid[x][y] == 'H':
                    self.playerGridButtons[x][y].configure(image=self.hitImg,state='disabled')
    def changeOponentSquareIcon(self):
        for x in range(self.size):
            for y in range (self.size):
                if Grid.oponentGrid[x][y]== 'H':
                    self.oponentGridButtons[x][y].configure(image=self.smallHitImg,state = 'disabled')
                elif Grid.oponentGrid[x][y] == '0':
                    self.oponentGridButtons[x][y].configure(image=self.smallEmptyImg,state = 'enabled')
                elif Grid.oponentGrid[x][y] == 'M':
                    self.oponentGridButtons[x][y].configure(image=self.smallMissImg,state = 'disabled')
                elif Grid.oponentGrid[x][y] =='B':
                    self.oponentGridButtons[x][y].configure(image=self.smallEmptyImg,state='enabled')
            

    def disableAllPlayerButtons(self):
        for i in range (self.size):
            for j in range (self.size):
                self.playerGridButtons[i][j].configure(state='disabled')
                self.oponentGridButtons[i][j].configure(state='enabled')
        self.rotateButton.configure(state='disabled')

        

        return


root = Tk()
menu_gui = MenuGUI(root)
root.mainloop()


